// Curated selector lists used by agent.js. Loaded into the same world first.
globalThis.__p2pSelectors = {
  // Cookie and consent banners from the common consent platforms.
  consent: [
    '#onetrust-consent-sdk',
    '#onetrust-banner-sdk',
    '.onetrust-pc-dark-filter',
    '#CybotCookiebotDialog',
    '#CybotCookiebotDialogBodyUnderlay',
    '#cookiebanner',
    '#cookie-banner',
    '#cookieBanner',
    '#cookie-notice',
    '#cookie-law-info-bar',
    '#cookie-bar',
    '.cookie-banner',
    '.cookie-notice',
    '.cookie-consent',
    '.cookie-bar',
    '.cc-window',
    '.cc-banner',
    '.cc-revoke',
    '#cc-main',
    '.qc-cmp2-container',
    '#qc-cmp2-container',
    '.fc-consent-root',
    '#usercentrics-root',
    '#usercentrics-cmp-ui',
    '#didomi-host',
    '#truste-consent-track',
    '.truste_box_overlay',
    '.truste_overlay',
    '#gdpr-cookie-message',
    '.osano-cm-window',
    '.osano-cm-dialog',
    '#hs-eu-cookie-confirmation',
    '.cky-consent-container',
    '.cky-overlay',
    '.cmplz-cookiebanner',
    '#moove_gdpr_cookie_info_bar',
    '#iubenda-cs-banner',
    '#axeptio_overlay',
    '[id^="sp_message_container"]',
    '.sp_veil',
    '#cmpbox',
    '#cmpbox2',
    '.cmpboxBG',
    '#consent_blackbar',
    '#BorlabsCookieBox',
    '.evidon-banner',
    '#ketch-consent-banner',
    '#transcend-consent-manager',
  ],

  // Chat and support launchers.
  chat: [
    '#intercom-container',
    '#intercom-frame',
    '.intercom-lightweight-app',
    '.intercom-launcher',
    '#hubspot-messages-iframe-container',
    '#drift-widget',
    '#drift-frame-controller',
    '#drift-frame-chat',
    'iframe#launcher',
    '#webWidget',
    '#crisp-chatbox',
    '.crisp-client',
    '#tidio-chat',
    '#fc_frame',
    '#chat-widget-container',
    '#beacon-container',
    '#gorgias-chat-container',
    '.tawk-min-container',
    'iframe[src*="tawk.to"]',
    '.olark-launcher',
    '#olark-wrapper',
    '.zopim',
    '#livechat-compact-container',
    '#smartsupp-widget-container',
    '#chatra',
    '#helpcrunch-container',
    '.woot-widget-holder',
    '.woot--bubble-holder',
  ],

  // Classes sites put on html/body to stop scrolling while a modal is open.
  lockClasses: [
    'modal-open',
    'no-scroll',
    'noscroll',
    'overflow-hidden',
    'is-locked',
    'scroll-lock',
    'scroll-locked',
    'has-modal',
    'disable-scroll',
    'no-overflow',
    'stop-scrolling',
    'lock-scroll',
    'body-lock',
    'is-modal-open',
    'overlay-open',
    'ReactModal__Body--open',
    'fancybox-active',
    'compensate-for-scrollbar',
  ],

  topNav: [
    'header',
    '[role="banner"]',
    'nav',
    '[role="navigation"]',
    '[id*="header" i]',
    '[class*="header" i]',
    '[class*="navbar" i]',
    '[id*="navbar" i]',
    '[class*="topbar" i]',
    '[class*="top-bar" i]',
    '[id*="masthead" i]',
    '[class*="masthead" i]',
    '[class*="announcement" i]',
    '[id*="announcement" i]',
  ],

  sideNav: [
    'aside',
    '[role="complementary"]',
    'nav',
    '[role="navigation"]',
    '[class*="sidebar" i]',
    '[id*="sidebar" i]',
    '[class*="side-bar" i]',
    '[class*="sidenav" i]',
    '[class*="side-nav" i]',
    '[class~="toc"]',
    '[id="toc"]',
    '[class*="table-of-contents" i]',
    '[class*="tableofcontents" i]',
    '[id*="table-of-contents" i]',
    '[data-toc]',
    '[class*="syllabus" i]',
    '[class*="curriculum" i]',
    '[class*="course-outline" i]',
    '[class*="lesson-list" i]',
    '[class*="chapters" i]',
    '[class*="playlist" i]',
    '[aria-label*="course materials" i]',
    '[aria-label*="table of contents" i]',
    '[aria-label*="outline" i]',
  ],

  footer: [
    'footer',
    '[role="contentinfo"]',
    '#footer',
    '.footer',
    '.site-footer',
    '[class*="site-footer" i]',
    '[id*="site-footer" i]',
    '#colophon',
  ],

  // Inline opacity:0 inside these is slide state, not a reveal animation.
  carousel: [
    '[class*="carousel" i]',
    '[class*="slider" i]',
    '[class*="swiper" i]',
    '[class*="slick" i]',
    '[class*="splide" i]',
    '[class*="glide" i]',
    '[class*="flickity" i]',
    '[aria-roledescription="carousel"]',
    '[aria-roledescription="slide"]',
  ],

  // Menus, tooltips and dialogs keep their hidden state.
  transient: [
    'nav',
    '[role="navigation"]',
    '[role="menu"]',
    '[role="menubar"]',
    '[role="listbox"]',
    '[role="tooltip"]',
    '[role="dialog"]',
    '[aria-modal="true"]',
    '[popover]',
    '[aria-hidden="true"]',
  ],

  lazySrc: [
    'data-src',
    'data-lazy-src',
    'data-original',
    'data-lazy',
    'data-echo',
    'data-ll-src',
    'data-hi-res-src',
    'data-full-src',
  ],
  lazySrcset: ['data-srcset', 'data-lazy-srcset', 'data-ll-srcset'],
  lazyBg: ['data-bg', 'data-background-image', 'data-bg-src', 'data-background'],
};
